### ISSUE TITLE
why the same?

### ISSUE THREAD

**Issue by Wjxfi** [SuhasDissa/Food-E-Web#1]
![0b613305-957c-4601-a3f1-d6835dbbe560.jpg](https://github.com/SuhasDissa/Food-E-Web/assets/113500363/d5f1e7d4-dbb1-43db-985d-c4cd8c55b715)

**Comment by SuhasDissa** [comment]
No, thats not what it means!
That page shows statistics about the database

For example there is 1 good additive (tumeric) and 0 bad and normal additives
currently added
(With 561 unknown health ratings)

**Comment by SuhasDissa** [comment]
I fixed the layout to be more self explanatory.
